name: Update index.html

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # Alt modülleri çekmek için bu parametreyi ekleyin

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python sürümünü seçin (örneğin 3.8)
     
      - name: rm index.html
        run: |
          rm index.html
          cp index_template index.html

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4  # BeautifulSoup kütüphanesini yükle


      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update index.html with new apps
        run: |
          python update_html.py  # Python script'inizi çalıştırın


      - name: Replace 'class_' with 'class' in index.html
        run: |
          sed -i 's/class_="cat"/class="cat"/g' index.html  # class_ -> class değiştirme

      - name: Commit changes
        run: |
          git add index.html
          git add repo/
          git commit -m "Update index.html with new apps" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
