name: Update index.html

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python sürümünü seçin (örneğin 3.8)

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

     
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Submodule'ları kullanma
          
      - name: Remove submodule references
        run: |
            if [ -d "repo" ]; then
             echo "Submodule 'repo' found, removing..."
             git submodule deinit -f --all
             git rm -f repo  # 'repo' yerine submodule adını yazın
             git commit -m "Remove submodule references"
             git push
            else
             echo "No submodule 'repo' found, skipping removal."
            fi


     
      - name: rm index.html
        run: |
          rm index.html
          cp index_template index.html

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4  # BeautifulSoup kütüphanesini yükle

      - name: clone repo
        run: |
          git clone https://github.com/APackage/A.P.A-repo repo
          git rm --cached repo

    

      - name: Update index.html with new apps
        run: |
          python update_html.py  # Python script'inizi çalıştırın


      - name: Replace 'class_' with 'class' in index.html
        run: |
          sed -i 's/class_="cat"/class="cat"/g' index.html  # class_ -> class değiştirme

      - name: Commit changes
        run: |
          git add index.html
          git commit -m "Update index.html with new apps" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
