name: Update HTML with Apps List

on:
  push:
    branches:
      - main  # Ana dalda değişiklik yapıldığında tetiklenecek

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Eğer başka bağımlılıklarınız varsa buraya ekleyin

    - name: Run Python script to update HTML
      run: python update_html.py  # Python script'ini çalıştırıyoruz

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update index.html with new apps"
        git push
